name: Nextvent CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if npm run test; then
            echo "Tests passed"
          else
            echo "No tests or tests failed, skipping"
          fi

      - name: Build Next.js app
        run: npm run build
